### ISSUE TITLE
Normalize color usage

### ISSUE THREAD

**Issue by josepjaume** [AjuntamentdeBarcelona/decidim-design#110]
#### :tophat: User Story
We should normalize color usage on the platform so call to actions (or at least, some of them) are derived from the primary colors, whereas success/destructive actions should use other colors.

Example:

![image](https://cloud.githubusercontent.com/assets/111746/21935599/687d7dfe-d9ae-11e6-8e26-58c7ca813a02.png)

In the screenshot, the main color is *red* but nonetheless call to actions are orange.

#### :clipboard: Related documentation
*None*

#### :dart: Acceptance criteria
Decidim deployments with overriden color variables are less rainbowy 🌈 

#### :pushpin: Related issues
*None*

**Comment by josepjaume** [comment]
@htmlboy @martuishere I've included the issue in the backlog as we'll have to deploy an installation next week and we'd need this solved. Is that ok?

**Comment by htmlboy** [comment]
@josepjaume I think we can take a look. Can we access the L'hospitalet installation to review that?

**Comment by oriolgual** [comment]
@htmlboy it's deployed here: http://decidim-hospitalet.herokuapp.com/

**Comment by josepjaume** [comment]
And, in case you're curious, the repo is there: https://github.com/HospitaletDeLlobregat/decidim-hospitalet

**Comment by martuishere** [comment]
@josepjaume @oriolgual I think I found the problem. The main color variables are defined in settings.scss, and this is the only place where they should be changed. However, in variables.scss we assign a different -shorter- variable name (ie, $primary instead of $primary-color), but the color remains the same. I suspect that in L'Hospitalet installation the color variable was changed in variables.scss but not in settings.scss, and this is why you are getting 2 different colors for the same variable 😕

To solve this mess, I suggest:

1. In L'Hospitalet, roll back variables.scss to the original declarations, and change the primary color in settings.scss.
2. I'll go over all the color declarations in the app and simplify them, so that they are only defined once (remove all $primary and change them for the more verbose but consistent $primary-color).
3. Divide and simplify settings.scss and make it more usable and better documented.
4. Document the color usage in the pattern library.

What do you think?

**Comment by josepjaume** [comment]
Can't we redefine `$primary-color` in `settings.scss` so it actually uses `$primary`?

```sass
$primary-color: $primary
```

I'm using `variables.scss` as an example file so implementors can change the variables that make most sense to them. I think of `settings.scss` as an **implementation detail** and `variables.scss` as the **actual public interface**. We should keep `variables.scss` organized, well-structured, clean, self-explanatory. We shouldn't care so much about `settings.scss` - the fact that `decididim's UI framework` uses it is just coincidental.

As for dividing and simplifying `settings.scss`, it's a secondary goal - we should probably check out the changes on Foundation `6.3.0` regarding that file as well.

What do you think? Am I making sense?

**Comment by josepjaume** [comment]
Here's an example of the actual CSS I'm writing for the `decidim-hospitalet` repo: https://github.com/HospitaletDeLlobregat/decidim-hospitalet/blob/master/app/assets/stylesheets/decidim.scss . As you can see, I'm just redefining one of the variables that were given to me as an example.

**Comment by martuishere** [comment]
I think the easiest way is to import `variables.scss` **into** `settings.scss`. That way, we can have our main variables in a separate file, and we can also reference them in the Foundation configuration file. It's not the prettiest solution, as we will still have the same color defined twice, but it's easy and shouldn't cause implementation problems.

Thoughts?

**Comment by josepjaume** [comment]
Well that won't be needed as settings.scss are loaded after variables.scss
right?

On Mon, Jan 16, 2017, 12:38 Marta Armada <notifications@github.com> wrote:

I think the easiest way is to import variables.scss *into* settings.scss.
That way, we can have our main variables in a separate file, and we can
also reference them in the Foundation configuration file. It's not the
prettiest solution, as we will still have the same color defined twice, but
it's easy and shouldn't cause implementation problems.

Thoughts?

—
You are receiving this because you were mentioned.
Reply to this email directly, view it on GitHub
<https://github.com/AjuntamentdeBarcelona/decidim-design/issues/110#issuecomment-272839040>,
or mute the thread

**Comment by martuishere** [comment]
No, right now `variables.scss` is loaded after `settings.scss`, but changing that won't solve the problem. 

What's happening right now is this:
- `$primary-color` is defined in `settings.scss`
- `background-color` of `.button` is set to `$primary-color` also in `settings.scss`
- color `$primary` is set to match `$primary-color` in `variables.scss`

It doesn't really matter when we load `variables.scss`, since Foundation makes us set the colors and the buttons in the same settings stylesheet.

If we don't want to change `settings.scss`, which I agree is a good idea, I see two possible alternatives:
- The pretty, but time consuming: dividing `settings.scss` into more manageable chunks that we can load when needed. This would also probably make `variables.scss` redundant, since we would only make changeable the variables that we are really using, and not all of Foundation defaults.
- The not-so-pretty, but easy and quick: insert `variables.scss`**inside** `settings.scss`, and change the buttons and other UI elements to use `$primary` instead of `$primary-color`. By doing this we could control all our variables in a single external stylesheet in a way that's both convenient and easy to understand, since there wouldn't be a need to mess with Foundation defaults.

I would go for the second option for now since it will fix several problems in the Hospitalet UI, and decide at a later stage if we want to make deeper changes to the CSS structure.

**Comment by josepjaume** [comment]
Okay, now I understsand the issue :). Let's go for option 2 then! :)
