### ISSUE TITLE
Document external sources (fonts, icons, libraries, etc.)

### ISSUE THREAD

**Issue by carolromero** [AjuntamentdeBarcelona/decidim-design#113]
#### :tophat: User Story

Add documentation for external sources. I couldn't find the icons license.
@htmlboy @martuishere are they part of some open source icon set?

**Comment by htmlboy** [comment]
@carolromero they are: https://useiconic.com/open

But I agree this should be better documented. Working on it soon.

**Comment by carolromero** [comment]
Thanks for the info @htmlboy. I noticed, though, that there are specific icons for components such as Meetings, Proposals, etc. and these are not part of the icon set.

Since we have new components like Surveys or Pages, we'll need new icons for them too.

![imagen](https://cloud.githubusercontent.com/assets/23509895/22056456/7c55da0a-dd60-11e6-8d54-0c3ced35f553.png)

**Comment by htmlboy** [comment]
The components have a special set of icons that were designed with the Decidim Barcelona logo. I'm not sure about the license in this particular case, but if we need more icons than the original set perhaps we should ask the designer? If we want to develop new components and keep using these icons, the components could share icons depending on the purpose, e.g.: "proposals" and "projects" could have the same icon, "Surveys" and "Debates" could share the same, any informative page could have de "info" icon… thoughts, @josepjaume?

You can find the original design in https://github.com/AjuntamentdeBarcelona/decidim-design/blob/master/source/docs/icons.pdf

<img width="1073" alt="screen shot 2017-01-18 at 18 04 41" src="https://cloud.githubusercontent.com/assets/468685/22074829/033b6f32-ddaa-11e6-8ed7-ffebbb34c4f2.png">

**Comment by josepjaume** [comment]
We could even let the end-user choose with a default. What do you think?

**Comment by htmlboy** [comment]
@josepjaume that might lead to inconsistencies that could have a negative impact in the UX. I would leave that option only for new components that don't have an assigned icon.

**Comment by carolromero** [comment]
> that might lead to inconsistencies that could have a negative impact in the UX. 

Agreed.

> If we want to develop new components and keep using these icons, the components could share icons depending on the purpose, e.g.: "proposals" and "projects" could have the same icon, "Surveys" and "Debates" could share the same, any informative page could have de "info" icon.

This is kind of tricky. For example, Proposals and Projects could share the same icon, since Projects are, in a way, an "evolution" of the Proposals.
I don't see, however, Debates and Surveys sharing the same one. Their functionality is completely different.

I guess the best option would be telling the designer to create new ones, but I'm not sure this is possible.
Thoughts @andreslucena @arnaumonty ?

**Comment by xabier** [comment]
The original icons are copyleft, the designer made everything copyleft by contract so we have it that way. I think it is a good idea to bet on a free/open iconset.

**PLEASE**: change icon for "process" it reads like a dollar symbol, and "once seen, you cannot unsee".

**Comment by arnaumonty** [comment]
Hey @htmlboy 

We need the following icons:
- Process (new one)
- Budgets (Basket)
- Surveys 
- Pages

All of them should follow the same style of the ([others](https://cloud.githubusercontent.com/assets/468685/22074829/033b6f32-ddaa-11e6-8ed7-ffebbb34c4f2.png)) 

We have the last ok.

**Comment by htmlboy** [comment]
Hi @arnaumonty,

I was already working on these icons, so here's a screenshot of what's already developed:

![screen shot 2017-02-02 at 13 39 41](https://cloud.githubusercontent.com/assets/468685/22553959/c7d6bfa8-e95e-11e6-91c8-e88c1609218b.png)


I've tried to keep the icons simple and as close as the original design as possible. In a nutshell:

- As I understood, the pages component would be an optional informative component, so it makes sense to use the information icon that is already in the set, since we're not using it anywhere right now. 
 
- Before completely changing the process icon, my suggestion is to rotate the current icon a bit, making it less looking like an S (or $) but keeping the same idea behind, that connects very well with the process' "steps bar". By rotating it to the right, it also gives the sense of a process "going forward".  

- The polls icon is a clipboard, close to the temporary icon used before. We considered other styles like a checkbox with a checkmark, but the checkmark is already being used for results, so it would create confusion. 
  
- I specifically avoided the concept of a shopping basket for the budget icon because it's commonly associated with an ecommerce, even though the shopping cart is more common. It's even in Mercadona's logo. By using this shape, we'd induce the user to think there's some kind of shop behind, or that they will have to pay/use their credit card at the end of the process, or that they are buying/choosing something for themselves, rather than make the right choice for the community/city.

For this reason, I've looked for a shape that is closer to the idea of preparing a budget: a pie chart. It also gives you a sense of balance in the choices you'll do: if you use 3/4 of the budget in one project, you'll have only 1/4 left, so choose wisely, etc.

Obviously this is just a proposal, and I'm open to suggestions, but bear in mind that we have a limited time to dedicate to this task, as I'm developing as well the admin panels and solving several bugs, and the platform allows to update or change the icons easily afterwards.

Please let me know what you think.

**Comment by carolromero** [comment]
They look great to me @htmlboy (the budget icon is well-thought-out)

**Comment by htmlboy** [comment]
@carolromero thank you very much! :-)

**Comment by xabier** [comment]
Bravo! espero que no sea tarde o aprovecho para sacar el tema (puede esperar): un icono de componente inminente es el de Seguimiento (de los resultados)

**Comment by htmlboy** [comment]
@xabier Lo apunto en el backlog! :-)

**Comment by josepjaume** [comment]
@xabier that feature would be under the "results" component.

**Comment by josepjaume** [comment]
So it's not a different cmponent but added metadata of a result :). What we need to do is expand that feature

**Comment by xabier** [comment]
@josepjaume you are right! but we need to think about this more carefully. I am not sure really on how to do this better. Specially how to link Result as a Component with Monitoring as a Phase. This is certainly no the place. No need for a component Icon for Monitoring-Seguiment right now. Sorry! At least we spotted and interesting discussion :)
