### ISSUE TITLE
Rethink participatory process components navigation and hierarchy

### ISSUE THREAD

**Issue by josepjaume** [AjuntamentdeBarcelona/decidim-design#60]
### :tophat: User Story
Having worked on the current design for participatory process components navigation, we've spotted several weaknesses that need to be addressed:

##### Components permission mayhem

Components are currently forced to behave in different ways depending on the step you're navigating from. This also forces the backend to have a knowledge not only about what a component can do *when a particular step is active*, but also *when a particular step has been active in the past but it isn't now*.

We could resort to make components *read-only* after they're not active anymore, but what's actually *read-only*?

A tricky example of behavior that's difficult to configure is, for example, comments on a proposal. Should we keep them open after the component is no longer active?

##### Component resources' multiple URLs
Since we're scoping the whole navigation to a particular step, we should also include the step in the URL. This also means that a resource shared in a particular step will *always be shown in that particular step*. 

So, what happens if a user shares a proposal that *can't be voted right now*, but will in the future? Shouldn't the future viewers of that URL be able to vote but instead show the resource in the past step?

##### Steps should be informative and mostly secondary
Steps shouldn't take over our navigation. Instead, they should be secondary information attached to components and resources. Components *behave* differently depending on the active step of the process, and users should be informed of that, but that's all.

##### Components as a first-class citizen
Derived from the previous paragraph: We can now promote components to a more prominent place in the navigation. Make components great again.

##### Simplify UX
Participating in a process now involves a pretty convoluted navigation path until you reach anything that's actionable. We [tried to mitigate this](https://github.com/AjuntamentdeBarcelona/decidim-design/commit/feb30c3461988a879b3c40cfa46ff8e82076f118) but the solution is far from perfect.

##### How to show a process' history?
**Idea**: Include that information in a particular resource, for example, a proposal. "This proposal was created during step X".
**Idea**: Show the steps timeline in the participatory process front page, expanded with the components in each participatory process.

### :clipboard: Related documentation
*None*

### :dart: Acceptance criteria
UX of participatory process is vastly simplified.

### :pushpin: Related issues
*None*

**Comment by xabier** [comment]
No really sure about the URLs, but in general component **tokens** (specific meetings, proposals, etc.) rarely appear more than once in a process, but component **types** do appear in different phases. Proposals are the exception to this rule, and their re-use on a different phase or step is due to the fact that we are separating creative and decisive phases: i.e. proposals are first made, then supported. This could be solved by actually merging together these two steps and activating support/voting latter on, but within the same step.

**Comment by josepjaume** [comment]
Interesting insights. Really don't know how to achieve a consistend model where there's *one* prominent exception. I still feel like associations between steps and types should be a bit more fluid. 

This *putting components first* approach doesn't mean we don't clearly display their temporal structure - I just means they're not part of the navigation tree.

Oh my, this is complex.

**Comment by josepjaume** [comment]
@xabier: Does it make sense for a process to have two kinds of proposal *types* being run on different steps (that is, collecting separate groups of proposals for different reasons)?

**Comment by josepjaume** [comment]
Here's some thoughts on the matter:

1. If we don't have the need to have *separate proposal collection processes* happening at the same time, we could treat the participatory process as a **bucket** in which we store the proposals themselves.

1. If we do that, we can consider "proposal collection" & "proposal voting" as two separate components, each one tied to a particular configuration in a particular step.

1. This would give us the option to have multiple collection phases to the same proposals, e.g.: The proposals are closed to officials first, then open to the rest of citizens. We could do the same for voting - first votes are reserved to citizens, then officials filter the rest.

1. This would also probably result in a better UX in the admin panel as well, as we wouldn't need to configure a component's behavior in multiple steps (flag hell).

1. If we agree that components can only be on a single step, then we don't have to put the step itself on the URL, as it can be uniquely deducted from its relationship with the participatory process (and shown to its according tab).

1. Some resources (**tokens**) should still need to be somehow decoupled from the step navigation, as they have a lifetime that spans through multiple steps.

I think we're probably heading somewhere with this. @htmlboy, @andreslucena, @xabier, @beagleknight, @oriolgual, @mrcasals, I'd appreciate some feedback on this 👍

**Comment by andreslucena** [comment]
I think it's better to first explain the needed features and then we think about the possible solutions. 

On a given process a proposal needs to have a "journey", since it's first created, until it's accepted,  with the possiblity to be denied. For instance: 
* A verified user creates a proposal. The proposals can receive comments. 
* Then a verified user can vote the proposals given a limited ammount of supports. For instance, a user can give 10 supports to proposals. The proposals can receive comments. Some of the proposals can be denied on this step for not having a minimal support. A proposal can be rejected on this step. 
* Then there is a phase where a technician needs to give an economical estimation of the passed proposals. Some of the proposals can be denied by not being in the administration competence. A proposal can be rejected on this step. 
* Finally, a verified user can vote given a limited budget. A proposal can be rejected on this step. 

This is a kind of proposal, one of the most complex. There should be configurations that depends on the process: 
* Geolocation: a proposal can have a marker on a Map. 
* By origin: some processes can have proposals from an official (Ajuntament) origin (as the PAM process). 
* By district: some processes can have proposals for a given District or for All the City (as the PAM process). There should be possible to filter by this on /proposals navegation. 
* On some processes, only process_admin role can create proposals.

**Comment by josepjaume** [comment]
@andreslucena nice feedback. I think all the use cases can be solved by providing a global configuration for the `proposals` feature (where you set the characteristics like having geolocation, categories, etc), with a separate `component` for each of the steps where you actually configure its flow (who can vote and how many votes she has available, for example).

This is really nice feedback, keep it coming!

**Comment by josepjaume** [comment]
Nearly finishing that, yay! 👏 @andreslucena @arnaumonty @htmlboy @AjuntamentdeBarcelona/developers
